WIP Add information Memories and Test Unit
glpi-project/android-inventory-library pull request #141
Opened 2018-09-10 19:06 UTC by Ivans51

### Changes description

Add Speed
Add Type

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Ivans51 |10|

### References

Closes #N/A
Related: https://github.com/flyve-mdm/android-inventory-library/issues/63
Depends on #N/A

2018-09-11 20:59 UTC, rafaelje commented on inventory/src/main/java/org/flyve/inventory/categories/Memory.java
> +     *  ````
Please remove this characters

2018-09-11 21:00 UTC, rafaelje requested changes
Please remove the characters on comment

2018-09-11 21:06 UTC, rafaelje approved these changes
Reviewed

2018-09-12 13:12 UTC, ajsb85 approved these changes

2018-09-12 13:37 UTC, merged