WIP Development section for versioning
glpi-project/android-inventory-library pull request #142
Opened 2018-09-11 18:51 UTC by Naylin15

### Changes description
Add new folder structure
Add script to update version list
Add dropdown for code documentation folders

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |2|

### References

Closes #N/A
Related #137 
Depends on #N/A

2018-09-12 13:12 UTC, ajsb85 approved these changes

2018-09-12 21:52 UTC, Naylin15 commented
I've been making tests to add the path to the folders

2018-09-13 14:21 UTC, ajsb85 requested changes
Hi, @Naylin15 
This branch has conflicts that must be resolved

2018-09-18 18:12 UTC, ajsb85 approved these changes

2018-09-18 19:31 UTC, rafaelje approved these changes

2018-09-18 19:31 UTC, merged