WIP Add Information about Hardware
glpi-project/android-inventory-library pull request #152
Opened 2018-09-17 21:43 UTC by Ivans51

### Changes description

Update USERID
Update LASTLOGGEDUSER
Update DATELASTLOGGEDUSER

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@ivans51 |8|

### References

Closes #N/A
Related: https://github.com/flyve-mdm/android-inventory-library/issues/61
Depends on #N/A

2018-09-25 21:23 UTC, ajsb85 approved these changes

2018-09-26 15:04 UTC, rafaelje requested changes

2018-09-26 15:04 UTC, rafaelje commented on inventory/src/main/java/org/flyve/inventory/categories/Hardware.java
> +            e.printStackTrace();
Add FILog and keep just with Exception type

2018-09-26 15:24 UTC, rafaelje approved these changes

2018-09-26 18:53 UTC, merged