refactor: extract a condition in a method
glpi-project/android-inventory-library pull request #190
Opened 2018-10-27 23:19 UTC by kevinesaa

make the regex in a constant field.
add a method to check if the string contains the regex.

### Changes description

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@ |1|

### References

Closes #N/A
Related #N/A
Depends on #N/A

2018-10-29 20:54 UTC, ajsb85 approved these changes

2018-11-01 18:35 UTC, Ivans51 commented on inventory/src/main/java/org/flyve/inventory/categories/CategoryValue.java
> +    private boolean hasCharToReplace(final String val)
Nice 👍 
But use braces the correct way, for example:
Correct:
try {
...
Instead of:
try
{

2018-11-01 18:37 UTC, Ivans51 commented
DCO error, commit incorrectly signed off, you can use --amend to solvent this, for example:
git --amend -s -m "refactor(category): extract a condition in a method"

2018-11-16 19:39 UTC, ajsb85 requested changes
Hi, @Ivans51 
Could you fix the conflicts and squash the PR with a proper commit message?

2018-11-16 19:56 UTC, merged